# Generates the OSpRad app icon from the same wavelength_to_rgb() spectral gradient
# used in the live plot, so the icon matches the app's own visual language. Run once;
# outputs are committed and consumed by the PyInstaller --icon flags and by the
# Android buildozer.py icon.filename patch.
#
# Also writes app/_icon_bundled.py: the same PNG's bytes embedded as a Python
# module, used by OSpRad.py for the in app window icon (title bar/taskbar, separate
# from the exe/APK's file icon). See pyproject.toml for why this isn't a packaged
# data file. Same trick as calibration_data.csv.
#
# Usage: python packaging/assets/generate_icon.py

import math
import os
import sys

from PIL import Image, ImageDraw

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'app'))
from plotting import wavelength_to_rgb  # noqa: E402

OUT_DIR = os.path.dirname(__file__)
APP_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'app')
SIZE = 256
BG = (28, 28, 28, 255)  # matches plotting.py's DARK theme background


def build_base(size):
    img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    margin = int(size * 0.06)
    radius = int(size * 0.18)
    draw.rounded_rectangle([margin, margin, size - margin, size - margin],
                            radius=radius, fill=BG)

    # Spectral gradient bars (380 to 750nm), standing in for the sensor's measured range.
    bar_left = int(size * 0.16)
    bar_right = int(size * 0.84)
    bar_top = int(size * 0.30)
    bar_bottom = int(size * 0.62)
    n = bar_right - bar_left
    for i in range(n):
        nm = 380 + (750 - 380) * (i / max(1, n - 1))
        r, g, b = wavelength_to_rgb(nm)
        color = (int(r * 255), int(g * 255), int(b * 255), 255)
        x = bar_left + i
        draw.line([(x, bar_top), (x, bar_bottom)], fill=color)

    # Bell shaped curve trace over the bars, echoing the live plot's line.
    curve_pts = []
    for i in range(n):
        t = i / max(1, n - 1)
        height = math.exp(-((t - 0.42) ** 2) / (2 * 0.22 ** 2))
        y = bar_bottom - height * (bar_bottom - bar_top) * 0.92
        curve_pts.append((bar_left + i, y))
    draw.line(curve_pts, fill=(250, 250, 250, 255), width=max(2, size // 85))

    return img


def main():
    base = build_base(SIZE)
    png_path = os.path.join(OUT_DIR, 'ospradicon.png')
    base.save(png_path)

    ico_path = os.path.join(OUT_DIR, 'ospradicon.ico')
    ico_sizes = [(s, s) for s in (16, 24, 32, 48, 64, 128, 256)]
    base.save(ico_path, sizes=ico_sizes)

    with open(png_path, 'rb') as f:
        png_bytes = f.read()
    bundled_path = os.path.join(APP_DIR, '_icon_bundled.py')
    with open(bundled_path, 'w') as f:
        f.write(
            "# Auto-generated by packaging/assets/generate_icon.py. Do not edit by\n"
            "# hand, re-run that script instead.\n"
            "\n"
            "PNG_BYTES = "
        )
        f.write(repr(png_bytes))
        f.write('\n')

    print('Wrote', png_path)
    print('Wrote', ico_path)
    print('Wrote', bundled_path)


if __name__ == '__main__':
    main()
