# Regenerates app/_font_bundled.py from packaging/assets/fonts/, embedding the Inter
# font files so every build (PyInstaller, pip, Android) carries them as a plain
# module, the same trick as _icon_bundled.py. Run whenever the fonts change, and
# commit the result.
#
# Usage: python packaging/assets/generate_bundled_font.py

import base64
import os

FONT_DIR = os.path.join(os.path.dirname(__file__), 'fonts')
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'app', '_font_bundled.py')
FONTS = ('Inter-Regular', 'Inter-SemiBold')

with open(os.path.join(FONT_DIR, 'OFL.txt')) as f:
    license_text = f.read()

with open(OUT, 'w') as f:
    f.write('# Auto-generated by packaging/assets/generate_bundled_font.py from\n'
            '# packaging/assets/fonts/. Do not edit by hand, re-run that script instead.\n\n')
    f.write('LICENSE_TEXT = %r\n\n' % license_text)
    f.write('# Base64 encoded TrueType files.\nFONTS = {\n')
    for name in FONTS:
        with open(os.path.join(FONT_DIR, name + '.ttf'), 'rb') as font:
            f.write('    %r: %r,\n' % (name, base64.b64encode(font.read()).decode('ascii')))
    f.write('}\n')

print('Wrote %s (%d bytes)' % (OUT, os.path.getsize(OUT)))
