# Compiles firmware/OSpRad_firmware.ino with arduino-cli and writes
# app/_firmware_bundled.py (version, Intel HEX and source), so the app can flash the
# firmware it was released with, offline, on every platform. Run whenever the
# firmware changes and commit the result; --check (used by CI) fails if the
# committed module no longer matches the sketch.
#
# Needs arduino-cli with arduino:avr@1.8.8 and Servo@1.3.0, the versions CI uses.
#
# Usage: python packaging/generate_bundled_firmware.py [--check]

import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SKETCH = os.path.join(REPO, 'firmware', 'OSpRad_firmware.ino')
OUT = os.path.join(REPO, 'app', '_firmware_bundled.py')
FQBN = 'arduino:avr:nano'


def compile_hex():
    work = tempfile.mkdtemp()
    try:
        sketch_dir = os.path.join(work, 'OSpRad_firmware')
        os.makedirs(sketch_dir)
        shutil.copy(SKETCH, sketch_dir)
        build = os.path.join(work, 'build')
        cli = os.environ.get('ARDUINO_CLI', 'arduino-cli')
        subprocess.run([cli, 'compile', '--fqbn', FQBN, '--output-dir', build, sketch_dir],
                       check=True, stdout=subprocess.DEVNULL)
        with open(os.path.join(build, 'OSpRad_firmware.ino.hex')) as f:
            return f.read()
    finally:
        shutil.rmtree(work, ignore_errors=True)


def render():
    with open(SKETCH) as f:
        source = f.read()
    version = re.search(r'^#define FIRMWARE_VERSION "([^"]+)"', source, re.M).group(1)
    return ('# Auto-generated by packaging/generate_bundled_firmware.py from\n'
            '# firmware/OSpRad_firmware.ino. Do not edit by hand, re-run that script instead.\n\n'
            'VERSION = %r\n\nHEX_TEXT = %r\n\nSOURCE_TEXT = %r\n'
            % (version, compile_hex(), source))


def main():
    text = render()
    if '--check' in sys.argv:
        with open(OUT) as f:
            if f.read() != text:
                sys.exit('app/_firmware_bundled.py is out of date with the firmware; run '
                         'python packaging/generate_bundled_firmware.py and commit it.')
        print('app/_firmware_bundled.py matches the firmware.')
        return
    with open(OUT, 'w') as f:
        f.write(text)
    print('Wrote %s' % OUT)


if __name__ == '__main__':
    main()
