# Regenerates app/_calibration_data_bundled.py from app/calibration_data.csv, so a
# pip install has a read-only copy to seed a writable one from. See pyproject.toml
# for why the CSV's text is embedded as a .py module.
#
# Run whenever app/calibration_data.csv changes, and commit the result.
#
# Usage: python packaging/generate_bundled_calibration.py

import os

APP_DIR = os.path.join(os.path.dirname(__file__), '..', 'app')
SRC = os.path.join(APP_DIR, 'calibration_data.csv')
OUT = os.path.join(APP_DIR, '_calibration_data_bundled.py')

with open(SRC, 'r', newline='') as f:
    csv_text = f.read()

with open(OUT, 'w') as f:
    f.write(
        "# Auto-generated by packaging/generate_bundled_calibration.py from\n"
        "# calibration_data.csv - do not edit by hand, re-run that script instead.\n"
        "\n"
        "CSV_TEXT = "
    )
    f.write(repr(csv_text))
    f.write('\n')

print('Wrote %s (%d bytes)' % (OUT, os.path.getsize(OUT)))
